version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
